import { Deck } from '@prisma/client';

export const mockDeck = (overrides: Partial<Deck> = {}): Deck => ({
  id: 'deck-uuid-1',
  name: 'Test Deck',
  description: 'A test deck',
  category: null,
  userId: 'user-uuid-1',
  isPublic: false,
  isActive: true,
  color: '#007AFF',
  icon: null,
  spacedRepetitionEnabled: true,
  dailyGoalCards: 20,
  maxNewCardsPerDay: 10,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  lastStudiedAt: null,
  totalCards: 0,
  cardsDueCount: 0,
  cardsNewCount: 0,
  cardsLearningCount: 0,
  cardsMasteredCount: 0,
  averageAccuracy: 0,
  averageStudyTimePerCard: 0,
  totalStudyTimeMinutes: 0,
  totalReviews: 0,
  tags: [],
  customFields: {},
  aiGenerated: false,
  aiGenerationPrompt: null,
  aiModelUsed: null,
  ...overrides,
});
