import { User } from '@prisma/client';

export const mockUser = (overrides: Partial<User> = {}): User => ({
  id: 'user-uuid-1',
  stytchUserId: 'stytch-user-123',
  email: 'user@example.com',
  passwordHash: null,
  appleId: null,
  name: 'Test User',
  displayName: null,
  profilePictureUrl: null,
  isActive: true,
  isPremium: false,
  emailVerified: true,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  lastLoginAt: null,
  studyPreferences: {},
  timezone: 'UTC',
  languagePreference: 'en',
  totalStudyTimeMinutes: 0,
  currentStreakDays: 0,
  longestStreakDays: 0,
  totalCardsReviewed: 0,
  totalDecksCreated: 0,
  overallAccuracyRate: 0,
  averageSessionLengthMinutes: 0,
  masteryRate: 0,
  ...overrides,
});
