"""Initial migration

Revision ID: 28a8c0e6e895
Revises: 
Create Date: 2025-07-20 00:00:40.187000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28a8c0e6e895'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('apple_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('study_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('total_cards_reviewed', sa.Integer(), nullable=False),
    sa.Column('total_decks_created', sa.Integer(), nullable=False),
    sa.Column('overall_accuracy_rate', sa.Float(), nullable=False),
    sa.Column('average_session_length_minutes', sa.Float(), nullable=False),
    sa.Column('mastery_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_apple_id'), ['apple_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('spaced_repetition_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_goal_cards', sa.Integer(), nullable=False),
    sa.Column('max_new_cards_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_studied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cards', sa.Integer(), nullable=False),
    sa.Column('cards_due_count', sa.Integer(), nullable=False),
    sa.Column('cards_new_count', sa.Integer(), nullable=False),
    sa.Column('cards_learning_count', sa.Integer(), nullable=False),
    sa.Column('cards_mastered_count', sa.Integer(), nullable=False),
    sa.Column('average_accuracy', sa.Float(), nullable=False),
    sa.Column('average_study_time_per_card', sa.Float(), nullable=False),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_generation_prompt', sa.Text(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decks_user_id'), ['user_id'], unique=False)

    op.create_table('learning_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acted_upon_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_insights_insight_type'), ['insight_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_insights_user_id'), ['user_id'], unique=False)

    op.create_table('performance_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(length=20), nullable=False),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_cards_reviewed', sa.Integer(), nullable=False),
    sa.Column('unique_decks_studied', sa.Integer(), nullable=False),
    sa.Column('overall_accuracy', sa.Float(), nullable=False),
    sa.Column('average_session_quality', sa.Float(), nullable=False),
    sa.Column('cards_mastered', sa.Integer(), nullable=False),
    sa.Column('cards_learned', sa.Integer(), nullable=False),
    sa.Column('study_streak_days', sa.Integer(), nullable=False),
    sa.Column('goal_achievement_rate', sa.Float(), nullable=False),
    sa.Column('average_session_length', sa.Float(), nullable=False),
    sa.Column('strongest_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weakest_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvement_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_metrics_metric_date'), ['metric_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_metrics_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('flashcards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'LEARNING', 'REVIEW', 'MASTERED', name='cardstatus'), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('correct_reviews', sa.Integer(), nullable=False),
    sa.Column('streak_correct', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_study_time_seconds', sa.Integer(), nullable=False),
    sa.Column('average_response_time_seconds', sa.Float(), nullable=False),
    sa.Column('perceived_difficulty', sa.Float(), nullable=False),
    sa.Column('learning_velocity', sa.Float(), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_generation_prompt', sa.Text(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcards_deck_id'), ['deck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcards_next_review_date'), ['next_review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcards_status'), ['status'], unique=False)

    op.create_table('study_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('session_name', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('cards_reviewed', sa.Integer(), nullable=False),
    sa.Column('cards_correct', sa.Integer(), nullable=False),
    sa.Column('cards_incorrect', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False),
    sa.Column('cards_new_studied', sa.Integer(), nullable=False),
    sa.Column('cards_graduated', sa.Integer(), nullable=False),
    sa.Column('cards_mastered', sa.Integer(), nullable=False),
    sa.Column('cards_reset', sa.Integer(), nullable=False),
    sa.Column('average_response_time_seconds', sa.Float(), nullable=False),
    sa.Column('total_think_time_seconds', sa.Integer(), nullable=False),
    sa.Column('fastest_response_seconds', sa.Float(), nullable=True),
    sa.Column('slowest_response_seconds', sa.Float(), nullable=True),
    sa.Column('session_quality_score', sa.Float(), nullable=False),
    sa.Column('focus_score', sa.Float(), nullable=False),
    sa.Column('difficulty_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('interruptions_count', sa.Integer(), nullable=False),
    sa.Column('target_cards', sa.Integer(), nullable=True),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('goal_achieved', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_deck_id'), ['deck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('retention_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flashcard_id', sa.UUID(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('days_since_last_review', sa.Integer(), nullable=False),
    sa.Column('retention_strength', sa.Float(), nullable=False),
    sa.Column('initial_strength', sa.Float(), nullable=False),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.Column('stability_factor', sa.Float(), nullable=False),
    sa.Column('review_context', sa.String(length=100), nullable=True),
    sa.Column('environmental_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retention_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_data_flashcard_id'), ['flashcard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_data_measurement_date'), ['measurement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_data_user_id'), ['user_id'], unique=False)

    op.create_table('review_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('flashcard_id', sa.UUID(), nullable=False),
    sa.Column('difficulty_rating', sa.Integer(), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_seconds', sa.Float(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('review_context', sa.String(length=100), nullable=True),
    sa.Column('ease_factor_before', sa.Float(), nullable=False),
    sa.Column('ease_factor_after', sa.Float(), nullable=False),
    sa.Column('interval_before_days', sa.Integer(), nullable=False),
    sa.Column('interval_after_days', sa.Integer(), nullable=False),
    sa.Column('repetitions_before', sa.Integer(), nullable=False),
    sa.Column('repetitions_after', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('multiple_attempts', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_of_day_hour', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_sessions_deck_id'), ['deck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_sessions_flashcard_id'), ['flashcard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_sessions_flashcard_id'))
        batch_op.drop_index(batch_op.f('ix_review_sessions_deck_id'))

    op.drop_table('review_sessions')
    with op.batch_alter_table('retention_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_data_user_id'))
        batch_op.drop_index(batch_op.f('ix_retention_data_measurement_date'))
        batch_op.drop_index(batch_op.f('ix_retention_data_flashcard_id'))

    op.drop_table('retention_data')
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_deck_id'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcards_status'))
        batch_op.drop_index(batch_op.f('ix_flashcards_next_review_date'))
        batch_op.drop_index(batch_op.f('ix_flashcards_deck_id'))

    op.drop_table('flashcards')
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_performance_metrics_metric_type'))
        batch_op.drop_index(batch_op.f('ix_performance_metrics_metric_date'))

    op.drop_table('performance_metrics')
    with op.batch_alter_table('learning_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_insights_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_insights_insight_type'))

    op.drop_table('learning_insights')
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decks_user_id'))

    op.drop_table('decks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_apple_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
